name: my-website
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: my-website
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          ghpagesprefix: https://lulunac27a.github.io/github-stat
          repository: lulunac27a/my-website
          ghtoken: ${{ secrets.ghrs_github_api_token }}
